### ISSUE TITLE
Not compatible with PHP 8

### ISSUE THREAD

**Issue by swampopus** [wp-statistics/pchart#1]
The primary reason is because in PHP 8, class constructors _must_ use __construct().

I wrote a full solution/explanation here: https://stackoverflow.com/questions/74422418/pchart-not-working-failing-with-errors-in-php-8-0

**Comment by mostafasoufi** [comment]
Good point, will make it compatible soon.

**Comment by rezathriii** [comment]
The compatibility check is done and the new version is released.
