### ISSUE TITLE
Original project was GPL (1, 2, 3) licensed

### ISSUE THREAD

**Issue by ernstki** [wp-statistics/pchart#2]
Hi everyone,

The [initial commit](https://github.com/wp-statistics/pchart/blob/83b9fc616864c5ab1f1e09111a0937b55659b740/LICENSE) to this repository added an MIT [`LICENSE`](../blob/master/LICENSE), but the pChart 1.x source files [are GPL](https://github.com/wp-statistics/pchart/blob/2f6ee62e3c8f81df9fa2df133dd0349b829345ce/src/pChart/pCache.php#L10). The original author's copyright notices were then removed in [aec9183](https://github.com/wp-statistics/pchart/commit/aec9183fd9f01f9e73a89cbe89a49e371c8b7182#diff-a33732eefb73be43bba62da65aa0d31eeed1ca8a3a66f605cde41f56b01f8f94).

I think this might just be an oversight? To re-license would technically require the original author's—and contributors'—permission.

I understand that there are jurisdictions where the original copyright/license aren't recognized or legally-enforceable, but the discrepancy makes it difficult for others to use or contribute to your fork. So may I respectfully recommend that the `LICENSE` and the README be updated to match the original author's license and copyright attribution?

See [szymach/c-pchart](https://github.com/szymach/c-pchart?tab=readme-ov-file#license) for another fork which seems to have made a similar mistake initially, then caught themselves.

Thanks, take care!

**Comment by mostafasoufi** [comment]
Hello,

I appreciate you bringing this to my attention. I will promptly archive the repository.

Best regards
